service: prices
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  logRetentionInDays: 14
  versionFunctions: false
  deploymentBucket:
    name: alcolina-sls-deployments-930581755718-sa-east-1
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:GetObject'
          Resource:
          - arn:aws:s3:::alcolina-pbras-prices/prices/pbras.prices.json
          - arn:aws:s3:::alcolina-pbras-prices/prices/stations/station=*/prices.json
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
          - arn:aws:s3:::alcolina-pbras-prices/prices/stations/station=*/prices.json

functions:
  app:
    image:
      name: appimage
      command:
        - alcolina.main.wsgi
    events:
      - httpApi: '*'


plugins:
  - serverless-offline

custom:
  serverless-offline:
    ignoreJWTSignature: true
